### ISSUE TITLE
donation_thanks depends on module report_aeroo

### ISSUE THREAD

**Issue by gurneyalex** [OCA/donation#10]
We ruled out of OCA addons depending on other addons not in OCA or in the core. 

Please remove the dependency or remove the module from OCA/donation.

**Comment by alexis-via** [comment]
Which alternative do you propose to report_aeroo ? I want OpenERP to output a report that can easily be edited by the user in a user-friendly environment such as a word processor. In this case, Odoo generates a template of thank you letter with the address of the donor and the "core" of the letter must then be written by the user. So, I cannot use reporting engines that generate PDF or HTML.

**Comment by gurneyalex** [comment]
@alexis-via well for now we don't have something matching this requirement. @faide showed me a very nice tool durint the OCA Code Sprint that he may want to share with the OCA to fill in this need, based on https://github.com/faide/py3o.template

Maybe we can gently nudge him into making the PR and then help him work on it to get this merged.  :wink: :wink:

**Comment by faide** [comment]
yes you can :)

On Thu, Jun 25, 2015 at 9:01 AM, Alexandre Fayolle <notifications@github.com

**Comment by alexis-via** [comment]
@gurneyalex I also discussed with @faide about this solution "py3o" during the last OCA code sprint in LLN. It seems great and can be an alternative to report_aeroo.

I promise that, if py3o becomes an OCA module, I'll re-write the donation_thanks module to use it and remove the dependency on report_aeroo.

So now the work to solve this issue is for @faire and his collegues :)

**Comment by faide** [comment]
:p

we are working on it! I hope to be able to propose report_py3o for
inclusion in OCA by end of july. The module works with odoo7 and 8 (and has
its odoo8 branch because the API has been migrated to v8).

I expect to work on the PR during a sprint this summer.

**Comment by gurneyalex** [comment]
@faide sorry for the long delay... This is great news. Please ping the contributors mailing list when this arrives.

**Comment by alexis-via** [comment]
I propose to close this issue, because it is related to a much wider issue: the need to have an ODT -based reporting engine in the OCA, in order to be able to generate a report that can easily be modified by the user.
