### ISSUE TITLE
Setting up a donation using SEPA method

### ISSUE THREAD

**Issue by davidloarte** [OCA/donation#116]
When setting up a donation using the SEPA method it returns the following error.

It does not create the journal entry as when done through an invoice.

Surely there is some kind of configuration that I do not know. 

I am using the Spanish chart of accounts.

The journal entry Draft Entry (* 17) (PAY0004) reached an invalid state relative to its payment.
To be consistent, the journal entry must always contains:
- one journal item involving the outstanding payment/receipts account.
- one journal item involving a receivable/payable account.
- optional journal items, all sharing the same account.

El asiento de diario Borrador de asiento (* 18) (PAY0003) alcanzó un estado no válido en relación con su pago.
Para ser coherente, la entrada del diario debe contener siempre:
- un apunte de diario que involucre la cuenta de pagos / recibos pendiente.
- un apunte de diario que implique una cuenta por cobrar / por pagar.
- apuntes opcionales del diario, todos compartiendo la misma cuenta.

**Comment by nibafa** [comment]
Hello

I have the same issue, is this a known issue?
