### ISSUE TITLE
Commit "[FIX] Qweb donation tax receipt report" missing in [9.0]

### ISSUE THREAD

**Issue by funbaker** [OCA/donation#31]
Hello,

the commit f9200f1a22dfa945ba792bbe3314fb99ee8ca739, which fixes an external id error, is missing in branch 9.0

Regards

**Comment by alexis-via** [comment]
@funbaker I don't work on v9, so there are certainly many fixes & improvements that would need to be backported from v10 to v9. Feel free to make a PR to backport stuff and I'll approve it. Working on v10 is also a good option :)

**Comment by funbaker** [comment]
Running ``git cherry -v 9.0 10.0 | grep "^\+"`` gives me the follow list (see attached file)
[git_cherry.txt](https://github.com/OCA/donation/files/1600907/git_cherry.txt)

Am i right to assume that [UPD] tagged commits are automatically commited and can be ignored?

**Comment by funbaker** [comment]
I'm making progress with backporting (https://github.com/humanilog/donation/tree/9.0-backport), but currently i have an issue for which i'm unsure how to correctly handle it.

The commit 5a27dfd8 references `base.default_user`,
but it seems to not exist or has the wrong values, which leads to the following exception to be thrown: https://github.com/odoo/odoo/blob/9.0/addons/mail/models/res_users.py#L48

Any idea about this?

Regards

**Comment by alexis-via** [comment]
As far as I can see, base.default_user was introduced in v10, it doesn't exist on v9.
