### ISSUE TITLE
donation with only inkind products has no number

### ISSUE THREAD

**Issue by tbaden** [OCA/donation#59]
There is a workaround in the donation module
https://github.com/OCA/donation/blob/56783adb18854b66c4046504c0755b62aa7ca43b/donation/models/donation.py#L391-L398

but the number field is a related field to move_id.name
https://github.com/OCA/donation/blob/56783adb18854b66c4046504c0755b62aa7ca43b/donation/models/donation.py#L144-L149
which results in an empty number, when you create a donation with only inkind products
![Bildschirmfoto 2019-09-13 um 16 14 54](https://user-images.githubusercontent.com/6755125/64869420-a9b5e800-d641-11e9-9b07-9d5af1fb5efd.png)

This makes it impossible to identify the donation later on.

My suggestion to fix this, is to use a sequence for donation, like in sale.order or account.invoice:
![Bildschirmfoto 2019-09-13 um 16 10 15](https://user-images.githubusercontent.com/6755125/64869584-e7b30c00-d641-11e9-9330-9d7d75fb6707.png)
As a default something like: DON-YYYY-{sequence}

What's your opinion on this?
@OCA/donation-maintainers 
@alexis-via 
@nikul-serpentcs

**Comment by alexis-via** [comment]
Fixed in the donation module in v14.
