### ISSUE TITLE
create a central configuration

### ISSUE THREAD

**Issue by tbaden** [OCA/donation#61]
add a new configuration page to res.config.settings for donation to keep the configuration central.

**Comment by joj828** [comment]
Configuration page for donation

**Comment by pedrobaeza** [comment]
I don't like very much this because when you haven't migrated all modules but appear on that configuration, it's misleading, and if not, it's very costly to maintain.

**Comment by tbaden** [comment]
@benbrich  as this is your topic, please some feedback to @pedrobaeza 
maybe on the short way, as we are all on the oca days?

**Comment by benbrich** [comment]
As agreed with @pedrobaeza we will implement the config for now and see how much effort will arise from it. Generally a more robust but as well user friedly aproach should be implemented.

**Comment by alexis-via** [comment]
On v14, we only have 1 company-wide setting in the donation module (Product for Donations via Credit Transfer). So having a dedicated config page just for 1 setting may be a bit over-kill...
