### ISSUE TITLE
[11.0] [IMP] blanking unusable items in donation journal

### ISSUE THREAD

**Issue by benbrich** [OCA/donation#62]
When creating a journal for donations, AFAIK the type needs to be bank in order to being able to do reconciliation. Due to the bank type the journal displays a lot of things in the accounting => dashboard which are not needed in a donations journal. These items should be blanked if the journal if allow_donation in the journal is true. List of items which are not needed from my point of view:
- Buttons ('New Statement', 'Import Statement')
- Actions New ('Import Statement', 'Send Money', 'Receive Money')

**Comment by MrTango** [comment]
@benbrich I'm working on it ;)

**Comment by MrTango** [comment]
we don't need the following fields:

View: 
- Bank statements

New:
- remove all 

Reconsil:
- remove all
