### ISSUE TITLE
[12.0] [IMP] donation_base

### ISSUE THREAD

**Issue by tbaden** [OCA/donation#80]
open for discussion

Improvements suggested in PR https://github.com/OCA/donation/pull/67

User default syntax for sequence (https://github.com/OCA/donation/pull/67#discussion_r390194177):
```
            if values.get('name', '/') == '/':
                seq = self.env['ir.sequence']
                values['name'] = seq.with_context(
                     date=date).next_by_code('donation.tax.receipt') or '/'
```

necessary try block?
https://github.com/OCA/donation/pull/67#discussion_r390188343

compute monetary field:
https://github.com/OCA/donation/pull/67#discussion_r390194340

**Comment by jarroyomorales** [comment]
Hi @tbaden ! As I said in the PR, I think we should use the standard way of getting the code sequence on creation.

Regarding the try block I have done some tests just in case and it is not necessary at all.

And about the monetary field, I am not sure if it should be computed or not. On `donation_base` it shouldnt for sure, but with the `donation` module installed it doesnt make any sense to have an amount that doesnt sum as the donation lines. At least an onchange would be good...

If we agree on some of these I can create a PR!

**Comment by tbaden** [comment]
@jarroyomorales yes please for the try block and the sequence, for the monetary computation I would like to have input from @benbrich and @alexis-via as they use it for their projects and know how customer use it.
