### ISSUE TITLE
Sending donation receipts by email to donors

### ISSUE THREAD

**Issue by sombatos** [OCA/donation#96]
Thanks for your work. Planning to install the Odoo. Just a quick question.

Is it possible to send donation receipts by email to donors? Or download them as PDF? Or get a link where the receipt can be viewed?

**Comment by alexis-via** [comment]
Yes, it's possible to send the tax receipt by email, cf https://github.com/OCA/donation/blob/14.0/donation_base/views/donation_tax_receipt.xml#L18
